from datetime import datetime

class ReportService:
    @staticmethod
    def generate_markdown_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a professional markdown report from scan results.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"# Defend & Detect Security Report\n"
        report += f"**Module**: {module_type}\n"
        report += f"**Date**: {timestamp}\n"
        report += f"**Input**: {input_data}\n\n"
        report += "---\n\n"
        
        if module_type == "PHISHING":
            hf = result_data.get("hf_result", {})
            groq = result_data.get("groq_result", {})
            report += "## Analysis Results\n"
            if hf.get("status") == "success":
                report += f"- **AI Model Prediction**: {hf['label']} ({hf['score']:.1%})\n"
            if groq.get("status") == "success":
                report += f"\n### Threat Report\n{groq['content']}\n"
                if groq.get("thought"):
                    report += f"\n### AI Reasoning Process\n{groq['thought']}\n"

        elif module_type == "URL":
            vt = result_data.get("vt_result", {})
            hf = result_data.get("hf_result", {})
            final = result_data.get("final_analysis", {})
            report += "## Threat Intelligence Highlights\n"
            if vt.get("status") == "success":
                stats = vt.get("stats", {})
                malicious = stats.get("malicious", 0)
                report += f"- **VirusTotal**: {malicious} malicious flags\n"
                if "message" in vt:
                    report += f"  - Status: {vt['message']}\n"
            if hf.get("status") == "success":
                report += f"- **Structural Analysis**: {hf['label']} ({hf['score']:.1%})\n"
            if final.get("status") == "success":
                report += f"\n### Unified Synthesis\n{final['content']}\n"
                if final.get("thought"):
                    report += f"\n### AI Reasoning Process\n{final['thought']}\n"

        elif module_type == "HASH":
            vt = result_data.get("vt_result", {})
            groq = result_data.get("groq_result", {})
            report += "## Fingerprint Analysis\n"
            if vt.get("status") == "success":
                stats = vt.get("stats", {})
                malicious = stats.get("malicious", 0)
                report += f"- **VirusTotal**: {malicious} engines detected malware\n"
                if "message" in vt:
                    report += f"  - Status: {vt['message']}\n"
            if groq.get("status") == "success":
                report += f"\n### AI Interpretation\n{groq['content']}\n"
                if groq.get("thought"):
                    report += f"\n### AI Reasoning Process\n{groq['thought']}\n"

        elif module_type == "CVE":
            nvd = result_data.get("nvd_result", {})
            groq = result_data.get("groq_result", {})
            report += "## Vulnerability Context\n"
            if nvd.get("status") == "success":
                report += f"- **NVD Severity**: {nvd.get('severity')} ({nvd.get('score')})\n"
            if groq.get("status") == "success":
                report += f"\n### AI Plain English Explanation\n{groq['content']}\n"
                if groq.get("thought"):
                    report += f"\n### AI Reasoning Process\n{groq['thought']}\n"

        elif module_type == "LOG":
            report += "## Log Translation\n"
            if result_data.get("status") == "success":
                report += f"\n### Human-Readable Alert\n{result_data['content']}\n"
                if result_data.get("thought"):
                    report += f"\n### AI Reasoning Process\n{result_data['thought']}\n"

        report += "\n---\n*Generated by Defend & Detect AI Platform*"
        return report
