from datetime import datetime

SCANNER_VERSION = "1.2.0"

class ReportService:
    @staticmethod
    def _get_metadata(module_type: str) -> dict:
        return {
            "platform": "Defend & Detect AI",
            "version": SCANNER_VERSION,
            "module": module_type,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

    @staticmethod
    def generate_json_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a professional JSON report with full metadata.
        """
        import json
        report_data = {
            "metadata": ReportService._get_metadata(module_type),
            "input": input_data,
            "analysis": result_data
        }
        return json.dumps(report_data, indent=4)

    @staticmethod
    def generate_text_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a structured plain text report.
        """
        meta = ReportService._get_metadata(module_type)
        report = f"DEFEND & DETECT SECURITY REPORT (v{meta['version']})\n"
        report += f"{'='*40}\n"
        report += f"Module    : {meta['module']}\n"
        report += f"Timestamp : {meta['timestamp']}\n"
        report += f"Input     : {input_data[:100]}{'...' if len(input_data) > 100 else ''}\n"
        report += f"{'-'*40}\n\n"
        report += "ANALYSIS RESULTS:\n"
        
        content = result_data.get("groq_result", {}).get("content") or \
                  result_data.get("final_analysis", {}).get("content") or \
                  result_data.get("content", "No analysis content available.")
        
        report += f"\n{content}\n"
        report += f"\n{'='*40}\n"
        report += "Generated by Defend & Detect AI Platform"
        return report

    @staticmethod
    def generate_markdown_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a professional markdown report with styled elements.
        """
        meta = ReportService._get_metadata(module_type)
        
        report = f"# Defend & Detect Security Report\n"
        report += f"> **Version**: `{meta['version']}` | **Module**: `{meta['module']}` | **Date**: `{meta['timestamp']}`\n\n"
        report += f"### 📥 Input Data\n`{input_data}`\n\n"
        report += "---\n\n"
        
        # Module-specific sections (re-using existing logic but formatted better)
        if module_type == "PHISHING":
            groq = result_data.get("groq_result", {})
            report += "## 🛡️ Phishing Analysis\n"
            report += groq.get("content", "No content available")

        elif module_type == "URL":
            vt = result_data.get("vt_result", {})
            final = result_data.get("final_analysis", result_data.get("groq_result", {}))
            report += "## 🔗 URL Threat Intelligence\n"
            if vt.get("status") == "success":
                report += f"- **VirusTotal Detection**: {vt['stats'].get('malicious', 0)} malicious flags\n\n"
            report += f"### AI Synthesis\n{final.get('content', 'No content')}"

        elif module_type == "HASH":
            vt = result_data.get("vt_result", {})
            groq = result_data.get("groq_result", {})
            report += "## 🔍 Fingerprint Analysis (SHA-256)\n"
            if vt.get("status") == "success":
                report += f"- **Reputation**: {vt['stats'].get('malicious', 0)} detections\n\n"
            report += f"### AI Interpretation\n{groq.get('content', 'No content')}"

        elif module_type == "CVE":
            nvd = result_data.get("nvd_result", {})
            groq = result_data.get("groq_result", {})
            report += "## 🛡️ Vulnerability Insights\n"
            if nvd.get("status") == "success":
                report += f"- **Severity**: {nvd.get('severity')} ({nvd.get('score')})\n\n"
            report += f"### Technical Explanation\n{groq.get('content', 'No content')}"

        elif module_type == "LOG":
            report += "## 📝 Log Translation\n"
            report += result_data.get("content", "No content available")

        report += "\n\n---\n*This report was generated by the Defend & Detect AI Security Platform.*"
        return report

    @staticmethod
    def generate_csv_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a CSV report for spreadsheet compatibility.
        """
        import csv
        import io
        output = io.StringIO()
        writer = csv.writer(output)
        
        meta = ReportService._get_metadata(module_type)
        writer.writerow(["Field", "Value"])
        writer.writerow(["Platform", meta["platform"]])
        writer.writerow(["Version", meta["version"]])
        writer.writerow(["Module", meta["module"]])
        writer.writerow(["Timestamp", meta["timestamp"]])
        writer.writerow(["Input", input_data])
        
        content = result_data.get("groq_result", {}).get("content") or \
                  result_data.get("final_analysis", {}).get("content") or \
                  result_data.get("content", "")
        writer.writerow(["Report Content", content])
        
        return output.getvalue()

    @staticmethod
    def generate_html_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a styled, premium HTML report.
        """
        meta = ReportService._get_metadata(module_type)
        content = result_data.get("groq_result", {}).get("content") or \
                  result_data.get("final_analysis", {}).get("content") or \
                  result_data.get("content", "No content").replace("\n", "<br>")
        
        # Simple HTML template with "Hacker" aesthetic accents
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; padding: 40px; background: #f4f7f6; }}
                .report-card {{ background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); max-width: 800px; margin: auto; border-top: 4px solid #00f5d4; }}
                .header {{ border-bottom: 2px solid #eee; margin-bottom: 20px; padding-bottom: 10px; }}
                h1 {{ color: #1a1a1a; margin-top: 0; }}
                .meta {{ font-size: 0.9em; color: #666; margin-bottom: 30px; }}
                .label {{ font-weight: bold; color: #00f5d4; }}
                .content {{ background: #fafafa; padding: 20px; border-radius: 8px; border-left: 4px solid #00f5d4; white-space: pre-wrap; }}
                .footer {{ margin-top: 40px; font-size: 0.8em; text-align: center; color: #999; }}
            </style>
        </head>
        <body>
            <div class="report-card">
                <div class="header">
                    <h1>Defend & Detect Security Report</h1>
                </div>
                <div class="meta">
                    <p><strong>Module:</strong> {meta['module']} | <strong>Version:</strong> {meta['version']}</p>
                    <p><strong>Generated:</strong> {meta['timestamp']}</p>
                    <p><strong>Input:</strong> <code>{input_data[:100]}{'...' if len(input_data) > 100 else ''}</code></p>
                </div>
                <div class="content">
                    {content}
                </div>
                <div class="footer">
                    &copy; 2026 Defend & Detect AI Platform. All rights reserved.
                </div>
            </div>
        </body>
        </html>
        """
        return html

