from datetime import datetime

class ReportService:
    @staticmethod
    def generate_json_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a JSON report from scan results.
        """
        import json
        report_data = {
            "platform": "Defend & Detect",
            "module": module_type,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "input": input_data,
            "results": result_data
        }
        return json.dumps(report_data, indent=4)

    @staticmethod
    def generate_text_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a plain text report from scan results.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report = f"DEFEND & DETECT SECURITY REPORT\n"
        report += f"===============================\n"
        report += f"Module: {module_type}\n"
        report += f"Date: {timestamp}\n"
        report += f"Input: {input_data}\n\n"
        report += "RESULTS:\n"
        
        # Simple extraction for text report
        if "groq_result" in result_data:
            report += f"AI Report: {result_data['groq_result'].get('content', 'No content')}\n"
        elif "final_analysis" in result_data:
             report += f"AI Report: {result_data['final_analysis'].get('content', 'No content')}\n"
        elif "status" in result_data and "content" in result_data:
             report += f"AI Report: {result_data['content']}\n"
             
        report += "\nGenerated by Defend & Detect AI Platform"
        return report

    @staticmethod
    def generate_markdown_report(module_type: str, input_data: str, result_data: dict) -> str:
        """
        Generates a professional markdown report from scan results.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"# Defend & Detect Security Report\n"
        report += f"**Module**: {module_type}\n"
        report += f"**Date**: {timestamp}\n"
        report += f"**Input**: {input_data}\n\n"
        report += "---\n\n"
        
        if module_type == "PHISHING":
            hf = result_data.get("hf_result", {})
            groq = result_data.get("groq_result", {})
            report += "## Analysis Results\n"
            if hf.get("status") == "success":
                report += f"- **AI Model Prediction**: {hf['label']} ({hf['score']:.1%})\n"
            if groq.get("status") == "success":
                report += f"\n### Threat Report\n{groq['content']}\n"
                if groq.get("thought"):
                    report += f"\n### AI Reasoning Process\n{groq['thought']}\n"

        elif module_type == "URL":
            vt = result_data.get("vt_result", {})
            hf = result_data.get("hf_result", {})
            # Handle both direct and nested keys
            final = result_data.get("final_analysis", result_data.get("groq_result", {}))
            report += "## Threat Intelligence Highlights\n"
            if vt.get("status") == "success":
                report += f"- **VirusTotal**: {vt['stats'].get('malicious', 0) if 'stats' in vt else 0} malicious flags\n"
            if hf.get("status") == "success":
                report += f"- **Structural Analysis**: {hf['label']} ({hf['score']:.1%})\n"
            if final.get("status") == "success":
                report += f"\n### Unified Synthesis\n{final['content']}\n"
                if final.get("thought"):
                    report += f"\n### AI Reasoning Process\n{final['thought']}\n"

        elif module_type == "HASH":
            vt = result_data.get("vt_result", {})
            groq = result_data.get("groq_result", {})
            report += "## Fingerprint Analysis\n"
            if vt.get("status") == "success":
                report += f"- **VirusTotal**: {vt['stats'].get('malicious', 0) if 'stats' in vt else 0} engines detected malware\n"
            if groq.get("status") == "success":
                report += f"\n### AI Interpretation\n{groq['content']}\n"
                if groq.get("thought"):
                    report += f"\n### AI Reasoning Process\n{groq['thought']}\n"

        elif module_type == "CVE":
            nvd = result_data.get("nvd_result", {})
            groq = result_data.get("groq_result", {})
            report += "## Vulnerability Context\n"
            if nvd.get("status") == "success":
                report += f"- **NVD Severity**: {nvd.get('severity')} ({nvd.get('score')})\n"
            if groq.get("status") == "success":
                report += f"\n### AI Plain English Explanation\n{groq['content']}\n"
                if groq.get("thought"):
                    report += f"\n### AI Reasoning Process\n{groq['thought']}\n"

        elif module_type == "LOG":
            report += "## Log Translation\n"
            if result_data.get("status") == "success":
                report += f"\n### Human-Readable Alert\n{result_data['content']}\n"
                if result_data.get("thought"):
                    report += f"\n### AI Reasoning Process\n{result_data['thought']}\n"

        report += "\n---\n*Generated by Defend & Detect AI Platform*"
        return report
